### ISSUE TITLE
Component behaviour changes despite no modifications to the parameters

### ISSUE THREAD

**Issue by alex-mitrevski** [ropod-project/napoleon_navigation#13]
Hi @cesar-lopez-mar,

Hope you're doing well and sorry for bothering you.

We've recently started experiencing very strange issues with the navigation where the robot's behaviour changes over time (by that I mean over multiple days) despite there being no changes to the configuration parameters nor to the platform itself. Perhaps you might have some insight why.

For instance, immediately after we came back from the hospital, we performed various tests in the university and the robot was behaving fine (e.g. even the right turn problem that we were experiencing before was resolved). A few days later, one of our students was doing tests and, all of a sudden, the problem was back.

This also happened to us last week. Since we continued having issues with the right turn, we reparameterised the component until the problem was gone; we then performed maybe 20 or so runs to verify that this is indeed the case. But then when @AhmedFaisal95 was testing on Saturday, the problem was back again.

I have verified that there are neither odometry nor localisation issues that would cause this problem.

Would you have any ideas why this might be happening? Could it be that, as @blumenthal hypothesised, some timing constraints are being violated? Anything else would be very strange since the component is otherwise supposed to be deterministic.

Thanks!

cc @sthoduka @Lakshadeep @DharminB

**Comment by cesar-lopez-mar** [comment]
Hi @alex-mitrevski !

I am doing good. Whenever I find the time I am happy to help. That is indeed quite strange!. I also would suggest to verify if the controller is being computed on time. Whenever the deadline is not me then the predictions will differ too much from the reality and strange behavior might appear. 

Also, I realized that one reason the way the velocities are scaled. If we predict that there is an object after certain seconds in the prediction we scaled down the velocity from the present on. So if my prediction horizon is too large, then the robot will slow down too early. SO that prediction horizon can be made shorter or re-think the way the velocities are adapted (only adapt parts of the prediction).

Hope my comments help!

**Comment by alex-mitrevski** [comment]
Thanks @cesar-lopez-mar!

> That is indeed quite strange!. I also would suggest to verify if the controller is being computed on time. Whenever the deadline is not me then the predictions will differ too much from the reality and strange behavior might appear.

To see if timing is really the problem, we have now isolated the navigation to run only on dedicated cores, while the other components run on the remaining cores. This should guarantee a rather stable frequency since there will be no interruptions from the rest of the system.

So far, this seems promising; the behaviour is back to being more predictable. But we will be testing this extensively to verify that there are no sporadic behaviour changes.

> Also, I realized that one reason the way the velocities are scaled. If we predict that there is an object after certain seconds in the prediction we scaled down the velocity from the present on. So if my prediction horizon is too large, then the robot will slow down too early. SO that prediction horizon can be made shorter or re-think the way the velocities are adapted (only adapt parts of the prediction).

We have indeed made various tests with a reduced prediction horizon, although that seemed to make the robot less safe. But I suppose we haven't found the optimal parameter setting there yet.

**Comment by alex-mitrevski** [comment]
Based on extensive testing during the week, it can be concluded that the allocation of napoleon to dedicated cores (introduced with https://github.com/ropod-project/automatic-startup/pull/1) seems to have indeed resolved the problem.

I'm thus closing the issue.
