### ISSUE TITLE
Problems while turning at the large junctions 

### ISSUE THREAD

**Issue by Lakshadeep** [ropod-project/napoleon_navigation#4]
Hi @cesar-lopez-mar 

During the tests carried out in the last 3 days, we had problems while turning at the large junction in front of the washrooms at BRSU
![IMG_0706](https://user-images.githubusercontent.com/5105501/63861073-7a994880-c9aa-11e9-9e96-170da9ff8b02.jpg)
During some runs, it tried to turn but failed, while in some runs it just moved straight and stopped like in the above screenshot.

Initially, there was a bug in the planner, because of which 2 continuous junctions were returned. Later this bug was fixed, but ropod still had problems while turning at that junction. 

This is how the assignments looked like after fixing the bug in the planner:
```
Hallway assignment: 1571 1570 
Hallway assignment: 1570 1595 
Intersection assignment: 1595 1596 
Hallway assignment: 1596 1601 
Hallway assignment: 1601 1602 
Hallway assignment: 1602 1607 
Hallway assignment: 1607 1608 
Hallway assignment: 1608 1613 
Hallway assignment: 1613 1614 
Hallway assignment: 1614 1619 
Hallway assignment: 1619 1620 
Hallway assignment: 1620 1623 
Intersection assignment: 1624 1621 1621 1628 1622 left 
Hallway assignment: 1621 1628 
Hallway assignment: 1628 1629 
Hallway assignment: 1629 1473 
Hallway assignment: 1473 1470 
Hallway assignment: 1470 1469 
Hallway assignment: 1469 1466 
Hallway assignment: 1466 1465 
Hallway assignment: 1465 1462 
Hallway assignment: 1462 1461 
Hallway assignment: 1461 1458
```
During some runs it tried to turn, however, it was not successful. You can find a rosbag for a failed turn here:
https://nextcloud.ropod.org/remote.php/webdav/ropod_shared/rosbags/2019/08/20190827-napoleon-nav-brsu-failure.bag
And video here:
https://nextcloud.ropod.org/remote.php/webdav/ropod_shared/videos/2019/08/napoleon_navigation_failed_turn_at_the_junction.MOV

**Comment by cesar-lopez-mar** [comment]
Hi @Lakshadeep , did you plot the shape of the areas?

**Comment by cesar-lopez-mar** [comment]
From the identifiers, I see an error in the assignments: Normally, the last point of the intersection assignment is the same as the next hallway assignment. When you see this kind of navigation errors is usually because the areas are not well defined. It is always good to make a check by plotting the areas as well.  Also, remember the intersection should be define with 4 points.

**Comment by cesar-lopez-mar** [comment]
It seems the points 1621 and 1622 are interchanged, is the clockwise rule in place for that intersection?

**Comment by Lakshadeep** [comment]
> Hi @Lakshadeep , did you plot the shape of the areas?

The plan will look like this since list of the areas are same
https://git.ropod.org/ropod/navigation/ropod_navigation/uploads/4e392a417435e3ccc877d4ea2d19ac88/generated_plan_brsu1.png

**Comment by Lakshadeep** [comment]
> Also, remember the intersection should be define with 4 points.

Yes, intersection have only 4 points

**Comment by Lakshadeep** [comment]
> It seems the points 1621 and 1622 are interchanged, is the clockwise rule in place for that intersection?

As per the anti-clockwise rule, they seem to be in the correct order

**Comment by cesar-lopez-mar** [comment]
> > It seems the points 1621 and 1622 are interchanged, is the clockwise rule in place for that intersection?
> 
> As per the anti-clockwise rule, they seem to be in the correct order

Mmm I recheck and actually for a left assignment my first comment was not correct. Is it possible to put numbers on the points in the areas plot? Then I can check what the correct order should be

**Comment by cesar-lopez-mar** [comment]
Hi @Lakshadeep , I noticed that in the config file the line 17 (#define MOBIDIK) should be commented out when the mobidik is not attached, that might explain the observed behavior.

**Comment by Lakshadeep** [comment]
Hi @cesar-lopez-mar I performed the tests yesterday by making above mentioned change.

First I tested it with a smaller plan (from C022 corridor to corridor on right, same as integration week tests), but this time by sending plan from planner interface. Turning at this junction was successful and it proves that assignments are correct.

Then I performed the tests from C022 corridor to the elevator. However, in this case, it was unsuccessful while turning left at the big junction in front of washrooms. I did 3 runs and in all 3 runs it did try to turn left, but every time it turned too much, so kind of performed U-turn and then stopped.  

This behaviour was consistent in all 3 runs, unlike last week when during some runs it just stopped and tried to turn sometimes.

**Comment by cesar-lopez-mar** [comment]
I found some bugs that I am solving. In the mean time I also found an error in the areas:
![missing_door](https://user-images.githubusercontent.com/24954605/64281058-9d030700-cf52-11e9-8334-6ee744a7894c.png)
The areas do not take the door from the hallway to BRSU entrance into account. I suggest take it as a junction as well.

**Comment by tue-ropod** [comment]
This is solved by applying the suggestions as mentioned above.
