### ISSUE TITLE
Problem while navigating around the trashcans in BRSU hallways

### ISSUE THREAD

**Issue by Lakshadeep** [ropod-project/napoleon_navigation#5]
Hi @cesar-lopez-mar 

During the tests, most of the times ropod was unable to move around the trashcans present in the BRSU hallways, however during some runs it successfully navigated around these trashcans like in the video here:
https://nextcloud.ropod.org/remote.php/webdav/ropod_shared/videos/2019/08/napleon_nav_brsu_hallway_full.MOV

**Comment by cesar-lopez-mar** [comment]
The overtaking functionality is not active since it needs to be modified to support contiguous hallways. Moreover it needs also the entities. One of the objectives for coming development days at BRSU will be to get to work the overtaking behavior.

In the mean time we can tune the planner to make the robot navigate a bit more to the left. We can do that this afternoon via Zoom.

**Comment by Lakshadeep** [comment]
> In the mean time we can tune the planner to make the robot navigate a bit more to the left. We can do that this afternoon via Zoom.

Okay, I am available today anytime after 2 pm, let me know what time works for you.

**Comment by cesar-lopez-mar** [comment]
Ok let's meet at 2pm

**Comment by cesar-lopez-mar** [comment]
As discussed, increase the threshold values in lines 17-18 of the config fle:
static constexpr double ENV_TCTW_SIZE = 0.05;       // d_cor 0.05 Too close too wall area size [m]
static constexpr double ENV_TRNS_SIZE = 0.20;       // d_trns 0.2 Transition area size [m]

set them to 0.10 and  0.30 respectively to make the robot navigate further from the left

**Comment by Lakshadeep** [comment]
Yesterday, I performed tests by changing the above parameters. Now it can navigate around the trashcans, but the motion is very unstable.

**Comment by cesar-lopez-mar** [comment]
The corridor width parameter needs to be increased as well (try 3.0)

**Comment by tue-ropod** [comment]
This was solved by increasing width corridor and add obstacles avoidance on navigation
