### ISSUE TITLE
Systematic errors along BRSU long route + incorrectly deciding that the goal has been reached

### ISSUE THREAD

**Issue by alex-mitrevski** [ropod-project/napoleon_navigation#6]
Hi @cesar-lopez-mar 

I ran the napoleon navigation (on the `feature/refactoring_plus_plannerSimTesting` branch) a few times today so that we can go through our long university route (to the bar where we have coffee in winter). To do this, I used the action interface with the plan from `napoleon_nav_plan_to_hochschulestrasse.yaml`. The generated plan looks reasonable (I was visualising the walls as you were doing during the integration week).

I made the following observations during the runs:
1. after the door that leads to the entrance, the robot was systematically trying to go to the left (and was thus exiting the path it was trying to follow), so I had to manually rotate it towards the direction where it was actually supposed to go
2. right at the entrance to the canteen, the robot was always heading into a pillar (once again, I had to manually turn it away so that it doesn't hit the pillar)
3. in two out of three runs, the component incorrectly decided that it had reached the goal (and then crashed) even though it had only made it to the entrance area of the university
4. in the one other run, the robot did make it to the end of the route, but I had to occasionally steer it away from the tables in front of the cafeteria and one bench later on

I collected a rosbag of one of the runs in which the robot almost crashed with the pillar in front of the canteen and then the component died. The rosbag is at https://nextcloud.ropod.org/index.php/apps/files/?dir=/ropod_shared/logging_data/20191008_BRSU&fileid=19568

Could you please take a look at the data when you have time? Since most of the failures are systematic, I hope it would not be very difficult to debug them.

Thanks!

**Comment by cesar-lopez-mar** [comment]
Hi Alex, as discussed in the last developers meeting, there are systematic localization and odometry errors that lead to this kind of issues.

**Comment by tue-ropod** [comment]
Hi Alex, as a suggestion, in the mean time that localization issues are solved, can you redesign a route in which you go always through small corridors? 

And about the incorrect odometry from the wheels... one solution can be to replace the wheels of the ropod by those of the NARKO  platform, not sure if that is a possibility.

**Comment by alex-mitrevski** [comment]
Hi Cesar,

> Hi Alex, as a suggestion, in the mean time that localization issues are solved, can you redesign a route in which you go always through small corridors?

We do in fact have multiple routes - one just down the corridor from the lab and then another one to the elevator. We however also wanted to test the long route as well in order to see how that works compared to the maneuver navigation.

> And about the incorrect odometry from the wheels... one solution can be to replace the wheels of the ropod by those of the NARKO platform, not sure if that is a possibility.

Unfortunately, I don't think that's an option since the Narko platform is used for running navigation experiments in parallel (using the LOC software stack).

> Hi Alex, as discussed in the last developers meeting, there are systematic localization and odometry errors that lead to this kind of issues.

Absolutely, but I do think there might be some algorithmic problems as well (or the generated plan violates some of the constraints of the component) since we observe the same incorrect behaviour in the exact same places. But maybe we can talk about this during today's developers' meeting.

Cheers

**Comment by alex-mitrevski** [comment]
As discussed on Thursday, issues 1 and 2 were caused by an incorrect route plan (the areas had to be marked as junctions). We did one test after the route was corrected and the behaviour of the robot was as expected.

Issue 4 is caused by the odometry problems with the platform.

Issue 3 is probably a minor bug somewhere, but I guess we can look at that during the next integration week.

**Comment by tue-ropod** [comment]
Hi Alex, do you have a rosbag when that happened? Maybe I can already do some analysis for next week. Is it happening in the new tests?
